[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

["osx-config-check"]
    type = "file"
    url = "https://github.com/kristovatlas/osx-config-check"
    exact = true
    stripComponents = 1
    refreshPeriod = "72h"
